version: '3.8'
services:
  postgres:
    image: postgres:12
    container_name: biketaxi-postgres
    environment:
      POSTGRES_DB: biketaxi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - biketaxi-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: biketaxi-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - biketaxi-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: biketaxi-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - biketaxi-net

  booking-service:
    image: sriharsha3/bikeriderapp:booking-service
    container_name: biketaxi-booking-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      # Add other environment variables as needed

  driver-matching-service:
    image: sriharsha3/bikeriderapp:driver-matching-service
    container_name: biketaxi-driver-matching-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      # Add other environment variables as needed

  frontend:
    image: sriharsha3/bikeriderapp:frontend
    container_name: biketaxi-frontend
    ports:
      - "3000:80"
    depends_on:
      - booking-service
      - driver-matching-service

  frontend-v2:
    image: sriharsha3/bikeriderapp:frontend-v2
    container_name: biketaxi-frontend-v2
    ports:
      - "3001:80"
    depends_on:
      - booking-service
      - driver-matching-service

volumes:
  postgres_data: 

networks:
  biketaxi-net:
    driver: bridge 