services:
  # Booking Service
  - type: web
    name: biketaxi-booking-service
    env: docker
    plan: free
    region: oregon
    rootDir: booking-service
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d1oauq3uibrs73chhlp0-a:5432/biketaxi
      - key: SPRING_DATASOURCE_USERNAME
        value: biketaxi_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: MGun3SgtKFC4E6TNp1o7UI0FbQV2ld8g
      - key: PORT
        value: 8080

  # Driver Matching Service
  - type: web
    name: biketaxi-driver-matching-service
    env: docker
    plan: free
    region: oregon
    rootDir: driver-matching-service
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d1oauq3uibrs73chhlp0-a:5432/biketaxi
      - key: SPRING_DATASOURCE_USERNAME
        value: biketaxi_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: MGun3SgtKFC4E6TNp1o7UI0FbQV2ld8g
      - key: PORT
        value: 8081

  # Frontend
  - type: web
    name: biketaxi-frontend
    env: docker
    plan: free
    region: oregon
    rootDir: main-ui
    envVars:
      - key: REACT_APP_BOOKING_SERVICE_URL
        value: https://biketaxi-booking-service.onrender.com
      - key: REACT_APP_DRIVER_MATCHING_SERVICE_URL
        value: https://biketaxi-driver-matching-service.onrender.com
      - key: REACT_APP_GOOGLE_MAPS_API_KEY
        sync: false  # Set this manually in Render dashboard 