spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/biketaxi
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Kafka configuration
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: booking-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8080

logging:
  level:
    com.taxi.booking: DEBUG
    org.springframework.kafka: WARN
    org.apache.kafka: WARN

# Custom configuration
app:
  kafka:
    enabled: true  # Set to true to enable Kafka
    topic: booking-events

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  endpoint:
    health:
      show-details: always
    mappings:
      enabled: true 